Repository invainn/ARIA, pull requests merged in 2019-05, with the labels that each got.

#232 Issue #181 -- Update Google Calendar
  client/src/components/AP-AdminPortal/ViewModifyEventsCalendar/ViewModifyEventsCalendar.js
  client/src/components/App/App.js
  client/src/components/SP-SharedPortal/EventsCalendar/EventsCalendar.js
Labels: refactor

#234 Issue # 233 -- Fix Theme On Non Portal Pages
  client/src/components/NP-NonPortal/ForgotPassword/ForgotPassword.js
  client/src/components/NP-NonPortal/Login/Login.js
  client/src/components/NP-NonPortal/RegisterNewUser/RegisterNewUser.js
Labels: bug

#237 Issue #236 -- Fix Card Links For Existing Components
  client/src/components/SP-SharedPortal/Dashboard/adminCards.js
  client/src/components/SP-SharedPortal/Dashboard/customerCards.js
  client/src/components/SP-SharedPortal/Dashboard/teacherCards.js
Labels: bug

#238 Features/create event
  client/package.json
  client/src/components/AP-AdminPortal/CreateAnEvent/CreateAnEvent.js
  client/src/components/AP-AdminPortal/CreateAnEvent/EventInfo.js
  client/src/components/AP-AdminPortal/CreateAnEvent/StudentInfo.js
  client/src/components/AP-AdminPortal/CreateAnEvent/TeacherInfo.js
  client/src/components/AP-AdminPortal/ViewModifyEventsCalendar/ViewModifyEventsCalendar.js
  client/src/components/App/App.js
  client/src/components/Utils/Pickers.js
  client/yarn.lock
  server/package.json
  server/src/class/Account.js
  server/src/class/Event.js
  server/src/index.js
  server/src/routes/admin.js
  server/yarn.lock
Labels: enhancement

#239 Implemented Add a Participant
  client/src/actions/AppActions.js
  client/src/components/App/App.js
  client/src/components/CP-CustomerPortal/MyParticipants/EnhancedTableHead.js
  client/src/components/CP-CustomerPortal/MyParticipants/MyParticipants.js
  client/src/containers/App/AppContainer.js
  client/src/containers/CP-CustomerPortal/MyParticipants/MyParticipantsContainer.js
  client/src/reducers/AppReducer.js
  server/src/class/Student.js
  server/src/index.js
  server/src/routes/account.js
  server/src/routes/customer.js
Labels: enhancement

#240 Finished event registration
  client/package.json
  client/src/components/CP-CustomerPortal/MyEnrollments/MyEnrollments.js
  client/src/components/CP-CustomerPortal/RegisterForAnEvent/EventTableHead.js
  client/src/components/CP-CustomerPortal/RegisterForAnEvent/OrderDetails.js
  client/src/components/CP-CustomerPortal/RegisterForAnEvent/ParticipantTableHead.js
  client/src/components/CP-CustomerPortal/RegisterForAnEvent/RegisterForAnEvent.js
  client/src/components/CP-CustomerPortal/RegisterForAnEvent/ReviewOrder.js
  client/src/components/CP-CustomerPortal/RegisterForAnEvent/SelectAnEvent.js
  client/src/components/CP-CustomerPortal/RegisterForAnEvent/SelectParticipants.js
  client/src/components/SP-SharedPortal/EventsCalendar/EventsCalendar.js
  client/yarn.lock
  server/src/class/EventRegistration.js
  server/src/routes/customer.js
Labels: enhancement

#241 Events and Students now propagate to corresponding teachers
  client/src/components/CP-CustomerPortal/MyEnrollments/EnhancedTableHead.js
  client/src/components/TP-TeacherPortal/MyStudents/EnhancedTableHead.js
  client/src/components/TP-TeacherPortal/MyStudents/MyStudents.js
  client/src/components/TP-TeacherPortal/StudentRegistrations/StudentRegistrations.js
  server/src/index.js
  server/src/routes/teacher.js
Labels: enhancement

#242 Fixed CustomerID missing sometimes during adding a participant
  client/src/actions/AppActions.js
  client/src/components/App/App.js
  client/src/components/CP-CustomerPortal/MyParticipants/MyParticipants.js
  client/src/containers/CP-CustomerPortal/MyParticipants/MyParticipantsContainer.js
  client/src/reducers/AppReducer.js
  server/src/routes/customer.js
Labels: enhancement

#243 Document Generator backend and Docker Swarm migration
  .circleci/config.yml
  client/Dockerfile-prod
  docgen/requirements.txt
  docgen/server.py
  docgen/test.json
  docker-compose-prod.yml
  docker-compose.yml
  res/aria-client-certificate.yml
  res/aria-client.yml
  res/aria-ingress.yml
  res/aria-server-certificate.yml
  res/aria-server.yml
  server/Dockerfile
  server/package.json
  server/src/index.js
  server/src/passport.js
  server/src/routes/admin.js
  server/tests/app.test.js
  server/yarn.lock
Labels: enhancement
