Repository invainn/ARIA, pull requests merged in 2019-04, with the labels that each got.

#159 Issue #157 -- Update CSS Forms and Layout
  client/package.json
  client/src/components/ForgotPassword/keyboard.jpg
  client/src/components/NP-NonPortal/ForgotPassword/ForgotPassword.js
  client/src/components/NP-NonPortal/Login/Login.js
  client/src/components/NP-NonPortal/RegisterNewUser/RegisterNewUser.js
Labels: enhancement, refactor

#161 Issue # 160 -- Update Dashboard Card Styling
  client/src/components/SP-SharedPortal/Dashboard/Dashboard.js
Labels: refactor

#164 Issue #103 -- Fix CSS Styling Propagation For Headings
  client/src/components/AP-AdminPortal/AddATeacher/AddATeacher.js
  client/src/components/AP-AdminPortal/CreateAnEvent/CreateAnEvent.js
  client/src/components/AP-AdminPortal/ModifyAnEvent/ModifyAnEvent.js
  client/src/components/AP-AdminPortal/ScheduleAnEvent/ScheduleAnEvent.js
  client/src/components/AP-AdminPortal/ScheduleCommandPerformance/ScheduleCommandPerformance.js
  client/src/components/AP-AdminPortal/UploadMusic/UploadMusic.js
  client/src/components/AP-AdminPortal/ViewModifyCommandPerformance/ViewModifyCommandPerformance.js
  client/src/components/App/App.js
  client/src/components/CP-CustomerPortal/CustomerAccount/CustomerAccount.js
  client/src/components/CP-CustomerPortal/MyEnrollments/MyEnrollments.js
  client/src/components/CP-CustomerPortal/MyParticipants/MyParticipants.js
  client/src/components/CP-CustomerPortal/RegisterForAnEvent/RegisterForAnEvent.js
  client/src/components/SP-SharedPortal/AboutNNMTA/AboutNNMTA.js
  client/src/components/SP-SharedPortal/Dashboard/teacherCards.js
  client/src/components/SP-SharedPortal/EventsCalendar/EventsCalendar.js
  client/src/components/SP-SharedPortal/FAQ/FAQ.js
  client/src/components/SP-SharedPortal/PortalDrawer/PortalDrawer.js
  client/src/components/TP-TeacherPortal/MyStudents/MyStudents.js
  client/src/components/TP-TeacherPortal/StudentRegistrations/StudentRegistrations.js
  client/src/components/TP-TeacherPortal/Tasks/Tasks.js
  client/src/components/TP-TeacherPortal/TeacherAccount/TeacherAccount.js
Labels: bug, refactor

#165 Fixed descriptions not being spaced properly.
  client/src/components/AP-AdminPortal/AddATeacher/AddATeacher.js
  client/src/components/AP-AdminPortal/CreateAnEvent/CreateAnEvent.js
  client/src/components/AP-AdminPortal/CreateAnEvent/EventInfo.js
  client/src/components/AP-AdminPortal/CreateAnEvent/StudentInfo.js
  client/src/components/AP-AdminPortal/CreateAnEvent/TeacherInfo.js
  client/src/components/AP-AdminPortal/ModifyAnEvent/ModifyAnEvent.js
  client/src/components/AP-AdminPortal/ScheduleAnEvent/ScheduleAnEvent.js
  client/src/components/AP-AdminPortal/ScheduleCommandPerformance/ScheduleCommandPerformance.js
  client/src/components/AP-AdminPortal/ViewModifyCommandPerformance/ViewModifyCommandPerformance.js
Labels: bug

#166 Fixed Drawer Width for Admin Drawer names
  client/src/components/NP-NonPortal/Shell/ShellHeader/ShellHeader.js
  client/src/components/SP-SharedPortal/Dashboard/Dashboard.js
  client/src/components/SP-SharedPortal/PortalDrawer/PortalDrawer.js
Labels: bug

#168 Features/upload music
  client/src/components/AP-AdminPortal/AddATeacher/AddATeacher.js
  client/src/components/AP-AdminPortal/UploadMusic/UploadMusic.js
Labels: enhancement

#167 Document Generation
  client/src/components/AP-AdminPortal/GenerateDocuments/SelectDocuments.js
Labels: enhancement

#169 Moved the button to the right of the page instead of the left where i…
  client/src/components/AP-AdminPortal/CreateAnEvent/CreateAnEvent.js
Labels: enhancement

#170 Added Braintree Drop-In for the Register for an Event Payment page
  client/package.json
  client/src/components/CP-CustomerPortal/RegisterForAnEvent/EventPayment.js
  client/src/components/CP-CustomerPortal/RegisterForAnEvent/RegisterForAnEvent.js
  client/yarn.lock
Labels: enhancement

#194 Refactored landing pages
  client/src/components/NP-NonPortal/ForgotPassword/ForgotPassword.js
  client/src/components/NP-NonPortal/Login/Login.js
  client/src/components/NP-NonPortal/RegisterNewUser/RegisterNewUser.js
Labels: bug

#207 Features/authentication
  client/.dockerignore
  client/Dockerfile
  client/Dockerfile-prod
  client/package.json
  client/public/index.html
  client/src/actions/AppActions.js
  client/src/actions/LoginActions.js
  client/src/actions/RegisterActions.js
  client/src/components/AP-AdminPortal/AddATeacher/AddATeacher.js
  client/src/components/AP-AdminPortal/CreateAnEvent/CreateAnEvent.js
  client/src/components/AP-AdminPortal/GenerateAndPrintDocuments/GenerateAndPrintDocuments.js
  client/src/components/AP-AdminPortal/ModifyAnEvent/ModifyAnEvent.js
  client/src/components/AP-AdminPortal/ScheduleAnEvent/ScheduleAnEvent.js
  client/src/components/AP-AdminPortal/ScheduleCommandPerformance/ScheduleCommandPerformance.js
  client/src/components/AP-AdminPortal/UploadMusic/UploadMusic.js
  client/src/components/AP-AdminPortal/ViewModifyCommandPerformance/ViewModifyCommandPerformance.js
  client/src/components/App/App.js
  client/src/components/CP-CustomerPortal/CustomerPortal.js
  client/src/components/NP-NonPortal/Login/Login.js
  client/src/components/NP-NonPortal/RegisterNewUser/RegisterNewUser.js
  client/src/components/SP-SharedPortal/Dashboard/Dashboard.js
  client/src/components/SP-SharedPortal/PortalDrawer/PortalDrawer.js
  client/src/components/TP-TeacherPortal/MyStudents/MyStudents.js
  client/src/components/TP-TeacherPortal/StudentRegistrations/StudentRegistrations.js
  client/src/components/TP-TeacherPortal/Tasks/Tasks.js
  client/src/components/TP-TeacherPortal/TeacherAccount/TeacherAccount.js
  client/src/config.js
  client/src/containers/App/AppContainer.js
  client/src/containers/NP-NonPortal/Login/LoginContainer.js
  client/src/containers/NP-NonPortal/RegisterNewUser/RegisterNewUserContainer.js
  client/src/containers/SP-SharedPortal/Dashboard/DashboardContainer.js
  client/src/containers/SP-SharedPortal/PortalDrawer/PortalDrawerContainer.js
  client/src/containers/noAuth.js
  client/src/containers/withAuth.js
  client/src/index.js
  client/src/reducers/AppReducer.js
  client/src/reducers/LoginReducer.js
  client/src/reducers/RegisterNewUserReducer.js
  client/src/reducers/index.js
  client/src/store.js
  client/yarn.lock
  docker-compose.yml
  res/aria-client.yml
  res/aria-server.yml
  server/.dockerignore
  server/Dockerfile
  server/package.json
  server/src/class/Account.js
  server/src/db.js
  server/src/index.js
  server/src/passport.js
  server/src/routes/account.js
  server/src/routes/app.js
  server/tests/integration.test.js
  server/yarn.lock
Labels: bug, enhancement

#218 Added toggle visibility to password field in Registration
  client/src/actions/RegisterActions.js
  client/src/components/NP-NonPortal/RegisterNewUser/RegisterNewUser.js
Labels: enhancement

#219 Removed options dropdown from ShellHeader
  client/src/components/NP-NonPortal/Shell/ShellHeader/ShellHeader.js
  client/src/components/NP-NonPortal/Shell/ShellHeader/ShellHeaderOptions/ShellHeaderOptions.js
Labels: refactor

#220 Cleaned up RegisterForAnEvent and added BrainTree payment with PayPal
  client/package.json
  client/src/components/CP-CustomerPortal/RegisterForAnEvent/CommandPerformance.js
  client/src/components/CP-CustomerPortal/RegisterForAnEvent/EventPayment.js
  client/src/components/CP-CustomerPortal/RegisterForAnEvent/OrderDetails.js
  client/src/components/CP-CustomerPortal/RegisterForAnEvent/RegisterForAnEvent.js
  client/src/components/CP-CustomerPortal/RegisterForAnEvent/ReviewOrder.js
  client/src/components/CP-CustomerPortal/RegisterForAnEvent/SelectAnEvent.js
  client/src/components/CP-CustomerPortal/RegisterForAnEvent/SelectParticipants.js
  client/src/components/NP-NonPortal/Shell/ShellHeader/ShellHeader.js
  client/yarn.lock
  res/aria-server.yml
  server/package.json
  server/src/index.js
  server/src/routes/payment.js
  server/yarn.lock
Labels: enhancement

#225 Issue #213 -- Add Auth to Routes
  client/src/components/App/App.js
Labels: enhancement, refactor

#230 Fixed links for Dashboard to route to appropriate drawer tab
  client/src/components/App/App.js
  client/src/components/SP-SharedPortal/AboutNNMTA/AboutNNMTA.js
  client/src/components/SP-SharedPortal/EventsCalendar/EventsCalendar.js
  client/src/components/SP-SharedPortal/FAQ/FAQ.js
  client/src/components/SP-SharedPortal/PortalDrawer/PortalDrawer.js
  client/src/containers/SP-SharedPortal/AboutNNMTA/AboutNNMTAContainer.js
  client/src/containers/SP-SharedPortal/EventsCalendar/EventsCalendarContainer.js
  client/src/containers/SP-SharedPortal/FAQ/FAQContainer.js
Labels: bug
